### PR TITLE
Related to #278. Fetching tags

### PR DESCRIPTION
**Pull request by mccartney**
Related to #278. Making Travis fetch tags

### CODE REVIEW

**Comment by mccartney** [comment]
cc @mwz

**Comment by mccartney** [comment]
The failures are `2.13` only. Merging.

**Comment by mwz** [comment]
I take it didn't help since we're seeing this in the logs:
>16:54:10.684Z  INFO probot: sksamuel/scapegoat: Found 1 releases
16:54:10.685Z  INFO probot: sksamuel/scapegoat: Draft release: untagged-d79439205a58a609cd68
16:54:10.685Z  INFO probot: sksamuel/scapegoat: No last release found
16:54:10.686Z  INFO probot: sksamuel/scapegoat: Fetching all commits for branch master
16:54:42.987Z  INFO probot: sksamuel/scapegoat: Updating existing draft release

https://github.com/sksamuel/scapegoat/runs/495710106?check_suite_focus=true

🤔

**Comment by mwz** [comment]
It was silly of me to suggest adding the tags to the travis pipeline as it obviously doesn't have any impact on the release drafter job, which runs using github actions 🤦‍♂ 

💡 
> Found 1 releases
would indicate to me that release drafter doesn't use the latest tag from the history to determine your latest version, but it uses actual Github releases, which means you would need to publish the [v1.4.1](https://github.com/sksamuel/scapegoat/releases/tag/v1.4.1) as an actual release and then I'm assuming that release drafter would infer a tag from that release. Worth giving it a go.

**Comment by sksamuel** [comment]
We can switch the whole build over to github actions if you prefer.

**Comment by mwz** [comment]
yeah that would be my preference, but in the meantime to get the release drafter working I think we just need to turn the latest tag into a Github release.

**Comment by mccartney** [comment]
OK. Should we revert this one then?

**Comment by mwz** [comment]
yes of course

**Comment by mwz** [comment]
Hey @mccartney, do you need any help getting the release drafter working?
My current working theory is that release drafter needs at least one github release to produce a draft with changes since that release, so I think the way to get it working would be to publish the [v1.4.1](https://github.com/sksamuel/scapegoat/releases/tag/v1.4.1) tag as a release.

**Comment by mccartney** [comment]
TBH I fail to understand what exactly needs to be done, but I can try to look around today.

> publish the v1.4.1 tag as a release.
This I don't understand, but let's work together to get things done :)

I understand that our release process (I haven't done that before and don't have permissions) has been:
- execute something in `sbt`
- which sets some tags in Git in Github
- but most importantly uploads signed JARs to Maven repository.

I am not sure if @sksamuel has some step-by-step procedure he follows.

And now this Release Drafter - what is it meant to do exactly? I thought it "only" publishes some information to Github Release feature as a read-only additional information. Like an automated and nicely formatted CHANGELOG. Or what else?

**Comment by mwz** [comment]
> TBH I fail to understand what exactly needs to be done, but I can try to look around today.
> 
> > publish the v1.4.1 tag as a release.

So to do that you need to:
- navigate to the releases tab on github
- click on the v1.4.1 tag
- click on edit tag in the top right
- provide release description (changelog) in the text field and
- click on publish release button

You need collaborator permissions on the repo to be able to edit releases, so you should be able to do this.

> And now this Release Drafter - what is it meant to do exactly? I thought it "only" publishes some information to Github Release feature as a read-only additional information. Like an automated and nicely formatted CHANGELOG. Or what else?

Release drafter will automatically maintain a draft of the upcoming release with all the prs merged since the last release (it will be visible only to collaborators until published as a release). Once you publish a new tag, you can then link it to the existing draft and the process will start again.

**Comment by mccartney** [comment]
OK. Thanks for all the steps. I was surprised I needed to type the changelog manually. But did so anyway.

**Comment by mwz** [comment]
Excellent, I hope now when the release drafter job is rerun next time something gets merged to master it should correctly detect all the changes since 1.4.1.

**Comment by mwz** [comment]
> I was surprised I needed to type the changelog manually.

That's exactly why I suggested using release drafter so this step can be automated 😄

**Comment by mccartney** [comment]
OK. Trying with #307

**Comment by mccartney** [comment]
We are getting closer, but not there yet. Now the draft mentions only this newest change #307. Not everything since 1.4.1
image

But I guess that's good enough for us. We can do one more release with a manual changelog. And then finally it should be able to pick up.

**Comment by mwz** [comment]
ok yeah that sounds good
I guess it's a perfect opportunity then to start using the labels I defined in the config [here](https://github.com/sksamuel/scapegoat/blob/master/.github/release-drafter.yml) to get those PRs nicely grouped into the following categories:

- Features (`feature`)
- Bug Fixes (`bug`, `false positive`)
- Maintenance (`chore`) and
- Dependency updates (`dependency-update`) which is already done automatically by mergify

**Comment by mccartney** [comment]
I agree. We need to sync the Github labels with these in the drafter YAML.

**Pull request merged**
