### PR TITLE
Fixing #419 - false positive on Variable Shadowing when passing a reference to a function

### PR DESCRIPTION
**Pull request by mccartney**

### CODE REVIEW

**Comment by sksamuel** [comment]
Tests are failing.

**Comment by mccartney** [comment]
> Tests are failing.

As intended :) 
This PR is in draft. I started with the unit test reproducing the issue. No fix yet.

**Comment by sksamuel** [comment]
lol sorry
blame it on the drink !!!!!

**Comment by mccartney** [comment]
Fixes #419

**Pull request merged**
