### PR TITLE
Add a release workflow.

### PR DESCRIPTION
**Pull request by mwz**
This PR adds a release workflow using sbt-ci-release.

Here is how it works:
1. This workflow gets run every time a PR is merged to master and publishes a snapshot release for each version defined in the build.sbt file (we agreed we would release for the latest version of 2.11 and the two recent releases of 2.12 and 2.13). The snapshot is in the following format, e.g. `1.4.2+11-01b5562a+20200328-1650-SNAPSHOT` - it comprises of the most recent tag + distance of the HEAD commit from the tag (11 in this case), SHA of the HEAD (01b5562a), the current timestamp and the suffix `-SNAPSHOT`.
2. This workflow also runs each time a new tag is pushed to the repo and publishes a new release using the tag as the new version. sbt-ci-release identifies automatically that it needs to release a regular version instead of a snapshot using the sbt-dynver plugin, which happens under the hood. sbt-ci-release also takes care of signing (using sbt-pgp) and obviously publishing to sonatype (via sbt-sonatype).

You can read more about how it works in the project repo https://github.com/olafurpg/sbt-ci-release.

Required set-up:
@sksamuel, I'm going to need you to do a set of steps on your end to make this work (you can follow the instruction in the sbt-ci-release repo, but here's a summary of what's required).
1. You need to create a new GPG key used for signing scapegoat, submit it to the Ubuntu's OpenPGP keyserver and the `PGP_PASSPHRASE` and `PGP_SECRET` env variables as github secrets (in the repo settings). The `PGP_SECRET` needs to be base64 encoded.
1. Add `SONATYPE_USERNAME` and `SONATYPE_PASSWORD` as secrets. Those are the credentials used to publish to oss.sonatype.org. If you don't want to use your personal credentials, you can get a new bot account created and added (with publishing rights) to the `com.sksamuel.scapegoat` org.

Let me know once all that is done so we can merge this PR and test publishing snapshots from master before we try to publish a new release. 

Notes:
- when you push a new tag it needs to include a version starting with a `v`, e.g. `v1.5.0` - I can see you've been following this rule anyway so that shouldn't be a problem.

Relates to #306.

### CODE REVIEW

**Comment by sksamuel** [comment]
I've added the sonatype username / password as secrets.
I'm not sure what I'm base 64 encoding for the PGP key ?

**Comment by mwz** [comment]
> I'm not sure what I'm base 64 encoding for the PGP key ?

- the `PGP_PASSPHRASE` is your (random) password you entered as the pgp passphrase - plain text
- the `PGP_SECRET` is your pgp secret key encoded using base64
  you can get the secret key like so: `gpg --armor --export-secret-keys keyId`
  also when base64 encoding it make sure you disable line wrapping so the entire string is on one line; a snippet from the readme:
  ```
  # macOS
  gpg --armor --export-secret-keys $LONG_ID | base64 | pbcopy
  # Ubuntu (assuming GNU base64)
  gpg --armor --export-secret-keys $LONG_ID | base64 -w0 | clip
  # Arch
  gpg --armor --export-secret-keys $LONG_ID | base64 | sed -z 's;\n;;g' | xclip -selection clipboard -i
  # FreeBSD (assuming BSD base64)
  gpg --armor --export-secret-keys $LONG_ID | base64 | clip
  ```

**Comment by sksamuel** [comment]
Ok, if I've done it right, you should be good to go.

**Comment by mwz** [comment]
Great, thanks @sksamuel. Let's merge it and see where we are (if everyone else is happy). I'll try and follow up with any fixes should this not work 👀

**Comment by sksamuel** [comment]
Do it :)

**Comment by mwz** [comment]
@mccartney can we give this a try?

**Comment by mccartney** [comment]
Merged. And how do we proceed now?

**Comment by mwz** [comment]
It appears that the snapshots were published correctly, see https://github.com/sksamuel/scapegoat/runs/550874656 and e.g. https://oss.sonatype.org/content/repositories/snapshots/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.13.1/

I'm going to verify the artifacts and check if they are working, but this looks good so far. We'll find out whether publishing the release works when you're ready to create a new release and you push a new tag.

**Pull request merged**
