### PR TITLE
 Fix scala version split and update versions

### PR DESCRIPTION
**Pull request by rtfpessoa**

### CODE REVIEW

**Comment by sksamuel** [comment]
I get this now.

```
sam@sam-hp:~/development/workspace/scapegoat$ sbt release
[info] Loading settings from plugins.sbt,credentials.sbt ...
[info] Loading project definition from /home/sam/development/workspace/scapegoat/project
[info] Updating ProjectRef(uri("file:/home/sam/development/workspace/scapegoat/project/"), "scapegoat-build")...
[info] Done updating.
[info] Loading settings from build.sbt,version.sbt ...
[info] Set current project to scalac-scapegoat-plugin (in build file:/home/sam/development/workspace/scapegoat/)
[info] Starting release process off commit: cba46268b7c2b9700033ced6e175bae0e11faae6
[info] Checking remote [origin] ...
[info] Setting scala version to 2.11.12
[error] java.lang.NoSuchMethodError: sbt.internal.KeyIndex$.apply(Lscala/collection/Iterable;Lscala/collection/immutable/Map;)Lsbt/internal/ExtendableKeyIndex;
[error] 	at sbtrelease.Load$.structureIndex(Load.scala:58)
[error] 	at sbtrelease.Load$.reapply(Load.scala:20)
[error] 	at sbtrelease.ReleaseStateTransformations$.switchScalaVersion(ReleaseExtra.scala:309)
[error] 	at sbtrelease.ReleaseStateTransformations$.$anonfun$runCrossBuild$2(ReleaseExtra.scala:319)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:86)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at sbtrelease.ReleaseStateTransformations$.$anonfun$runCrossBuild$1(ReleaseExtra.scala:318)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.filterFailure$1(ReleasePlugin.scala:176)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$6(ReleasePlugin.scala:189)
[error] 	at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:86)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$2(ReleasePlugin.scala:194)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:136)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:129)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: sbt.internal.KeyIndex$.apply(Lscala/collection/Iterable;Lscala/collection/immutable/Map;)Lsbt/internal/ExtendableKeyIndex;
```

**Comment by rtfpessoa** [comment]
That might be related to my update of sbt to 1.1.
Can you try to update sbt-release to `addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.7")` or just revert my version changes and keep only the plugin fix.

**Comment by sksamuel** [comment]
Trying now.

**Comment by sksamuel** [comment]
1.3.5 has been released to central.

**Comment by sksamuel** [comment]
Thanks for your help.

**Comment by rtfpessoa** [comment]
No problem. Thanks a lot for your quick update and patience.

**Pull request merged**
