### PR TITLE
#211 Fix enum values comparison and added tests

### PR DESCRIPTION
**Pull request by xplosunn**

### CODE REVIEW

**Comment by rtfpessoa** [comment]
This is amazing, can't wait for this to be merged. No more bugs in legacy code because of this. 😍

**Comment by sksamuel** [comment]
:+1:

**Comment by rtfpessoa** [comment]
@sksamuel do you plan to do a release soon?

**Comment by sksamuel** [comment]
1.3.8 is released.
Give it 10 minutes to show up
http://repo1.maven.org/maven2/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.12/

**Comment by rtfpessoa** [comment]
Amazing. Thanks for the quick review and publish.

**Pull request merged**
